name: Node CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  GITHUB_API_TOKEN: ${{ secrets.GH_PAT }}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: checkout
        uses: actions/checkout@v2

      - name: npm ci
        run: npm ci

      - name: lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - name: setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: checkout
        uses: actions/checkout@v2

      - name: npm ci
        run: npm ci

      - name: test
        run: npm run test

  build:
    runs-on: ubuntu-latest

    steps:
      - name: setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: checkout
        uses: actions/checkout@v2

      - name: npm ci
        run: npm ci

      - name: build
        run: npm run build

      - name: save build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build

      - name: publish pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
